---
language: go
go:
  - 1.9.x
jobs:
  include:
    - stage: format check
      script: ./fmtpolice
    - stage: tests
      script: go test -v ./...
    - stage: integration tests
      script: go test -tags integration -v ./...
      if: branch = master
notifications:
  email:
    recipients:
      - webteam@himalayaninstitute.org
    on_success: never
    on_failure: change
